<a href="https://colab.research.google.com/github/biukaC/DA-Internship-ProgUA/blob/main/Final_cleaning_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [248]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [249]:
import pandas as pd
import numpy as np

In [250]:
final=pd.read_csv('https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/copy.csv')
cleaned=final.copy()
cleaned.head()

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Modified on,Modified by,Closed at,Tags,Note 2,...,Created filled,utm_source,utm_medium,utm_campaign,utm_term,utm_content,utm_referrer,phone,email,note_full
0,63408688,[NEW] free-data-analytics — /ua/free/data-anal...,0,Vasyl F.,2026-04-06 11:37:01,2026-04-06 11:39:26,Ivan M.,NaN,NaN,NaN,...,2026-04-06 11:37:01,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380732768040,gpossk469@yahoo.com,'=== First Touch ===\nutm_source: meta\nutm_me...
1,63408012,[NEW] free-data-analytics — /ua/free/data-anal...,0,Oksana B.,2026-04-06 10:40:14,2026-04-06 10:45:17,Ivan M.,NaN,NaN,NaN,...,2026-04-06 10:40:14,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380994950580,rgdxg618@gmail.com,'=== First Touch ===\nutm_source: meta\nutm_me...
2,63407286,form851431729,0,Vasyl F.,2026-04-06 09:42:58,2026-04-06 10:07:01,Vasyl F.,NaN,"no1, quiz-200125",NaN,...,2026-04-06 09:42:58,NaN,NaN,NaN,NaN,NaN,https://prog.academy/ua/quiz#apply,'+380682149696,kvhfupi462@meta.ua,FE: 10\nDA: 2\nQA: 2
3,63407150,Lead #63407150,0,Vasyl F.,2026-04-06 09:29:40,2026-04-06 10:06:57,Vasyl F.,NaN,NaN,NaN,...,2026-04-06 09:29:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63407124,[NEW] free-data-analytics — /ua/free/data-anal...,0,Natalia H.,2026-04-06 09:26:11,2026-04-06 10:10:57,Ivan M.,NaN,NaN,NaN,...,2026-04-06 09:26:11,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380630563876,udbzpt476@meta.ua,'=== First Touch ===\nutm_source: meta\nutm_me...


In [251]:
print(cleaned.shape)

(658, 42)


In [252]:
cleaned.columns

Index(['ID', 'Lead title', 'Lead sale ₴', 'Respons. user', 'Created on',
       'Modified on', 'Modified by', 'Closed at', 'Tags', 'Note 2',
       'Lead stage', 'Fullname', 'Contact`s company', 'Contact respons. user',
       'Telegram', 'Оплата', 'Курс', 'Lead scoring', 'Название пакета', 'Язык',
       'REFERER', 'FORMID', 'TRANID', 'COOKIES', 'Вопрос 1', 'Вопрос 2',
       'Вопрос 3', 'Вопрос 4', 'Вопрос 5', 'gclid', 'from', 'referrer',
       'Created filled', 'utm_source', 'utm_medium', 'utm_campaign',
       'utm_term', 'utm_content', 'utm_referrer', 'phone', 'email',
       'note_full'],
      dtype='object')

In [253]:
cleaned['Lead sale ₴'].unique()

array([    0,  5000, 40000, 15000, 20000, 45000, 10000, 25000])

In [254]:
cleaned['Lead sale ₴'] = cleaned['Lead sale ₴'].astype('float64')

In [255]:
cleaned['phone'].unique()

array(["'+380732768040", "'+380994950580", "'+380682149696", nan,
       "'+380630563876", "'+380681156697", "'+380929654137",
       "'+380996452646", "'+380937181375", "'+380919463414",
       "'+380735384839", "'+380684630839", "'+380637007335",
       "'+380927789135", "'+380955972558", "'+380738252172",
       "'+380987050555", "'+380917754839", "'+380969367425",
       "'+380981159241", "'+380918134285", "'+380666239133",
       "'+380677871834", "'+380500346729", "'+380631811216",
       "'+380945182000", "'+380736313518", "'+380979140237",
       "'+380910130027", "'+380667570917", "'+380638029248",
       '+380979402003', "'+380966575986", "'+380992079575",
       "'+380956763879", "'+380981423069", "'+380505933280",
       "'+380731860396", "'+380667179614", "'+380503560227",
       "'+380991894467", "'+380500148235", "'+380972542733",
       "'+380950701864", "'+380689593034", "'+380910298468",
       "'+380968646155", "'+380928930663", "'+380506593358",
       "'+3809471433

In [256]:
cleaned['phone'] = (cleaned['phone']
               .fillna('')
               .astype(str)
               .str.replace(r'(?!^\+)[^\d]', '', regex=True)
               .str.strip())

print(cleaned['phone'].str.len().value_counts())


phone
12    509
0      91
13     58
Name: count, dtype: int64


In [257]:
mask = (
    cleaned['phone'].notna() &
    (cleaned['phone'] != '') &
    ~cleaned['phone'].str.startswith('+')
)

cleaned.loc[mask, 'phone'] = '+' + cleaned.loc[mask, 'phone']

In [258]:
print(cleaned['phone'].str.len().value_counts(dropna=False))

phone
13    567
0      91
Name: count, dtype: int64


In [259]:
cleaned['Respons. user'].unique()

array(['Vasyl F.', 'Oksana B.', 'Natalia H.', 'Ivan M.'], dtype=object)

In [260]:
cleaned['Respons. user'].astype(str).str.strip()

,Respons. user
0,Vasyl F.
1,Oksana B.
2,Vasyl F.
3,Vasyl F.
4,Natalia H.
...,...
653,Vasyl F.
654,Natalia H.
655,Vasyl F.
656,Vasyl F.


In [261]:
cleaned['course_name'] = (
    cleaned['Lead title']
    .combine_first(cleaned['Курс'])
    .combine_first(cleaned['Название пакета'])
    .fillna('not provided')
    .astype(str)
)

cleaned = cleaned.drop(columns  = [
    'Lead title',
    'Курс',
    'Название пакета'
    ]
)
cleaned['course_name'].head(20)

,course_name
0,[NEW] free-data-analytics — /ua/free/data-anal...
1,[NEW] free-data-analytics — /ua/free/data-anal...
2,form851431729
3,Lead #63407150
4,[NEW] free-data-analytics — /ua/free/data-anal...
5,[NEW] free-data-analytics — /ua/free/data-anal...
6,[NEW] free-data-analytics — /ua/free/data-anal...
7,[NEW] free-data-analytics — /ua/free/data-anal...
8,[NEW] free-data-analytics — /ua/free/data-anal...
9,[NEW] free-data-analytics — /ua/free/data-anal...


In [262]:
cleaned['Lead stage'].unique()

array(['Заявка', 'ЯЩ (я еще горячий, но уже остываю)', 'Недозвон',
       'Закрыто и не реализовано (наберет сам если решит)',
       'Приглашен на ивент', 'Закрыто и не реализовано (спам)',
       'Принимает решение',
       'Закрыто и не реализовано (перестал отвечать в чате)',
       'Закрыто и не реализовано (не актуально)', 'Получили квитанцию',
       'Получил материалы', 'Закрыто и не реализовано',
       'Закрыто и не реализовано (недозвон)',
       'Закрыто и не реализовано (нет нужного курса)',
       'Закрыто и не реализовано (неправильный номер)',
       'Закрыто и не реализовано (перестал брать трубку)',
       'Закрыто и не реализовано (дорого)',
       'Закрыто и не реализовано (купил у конкурентов)',
       'Записан на пробное занятие', 'Получена предоплата',
       'Закрыто и не реализовано (передумал)', 'Успешно реализовано',
       'ОЖОП (ожидается оплата)'], dtype=object)

In [263]:
cleaned['Lead stage'] = cleaned['Lead stage'].str.replace(r'\s*\(.*?\)', '', regex=True)

In [264]:
cleaned['Lead stage'].unique()

array(['Заявка', 'ЯЩ', 'Недозвон', 'Закрыто и не реализовано',
       'Приглашен на ивент', 'Принимает решение', 'Получили квитанцию',
       'Получил материалы', 'Записан на пробное занятие',
       'Получена предоплата', 'Успешно реализовано', 'ОЖОП'], dtype=object)

In [265]:
cleaned['Оплата'].unique()

array(['Нет', nan, 'Monobank частями', 'Монобанк ФОП - Новый',
       'WayForPay (USD)', 'WayForPay (EUR)', 'USDT', 'Wise (EUR)',
       'Приват банк - Юлия', 'WayForPay (PLN)'], dtype=object)

In [266]:
cleaned['Contact respons. user'].unique()

array(['Vasyl F.', 'Oksana B.', 'Natalia H.', 'Ivan M.'], dtype=object)

In [267]:
cleaned['gclid'].unique()

array([nan,
       'rECiXPy_JPjrxqg3Htze9g5qp972K76O-a9uSJKamgtWqZLOQ9KwyN4u2wWIFBJS',
       'lb__LkWTNOXKyXsJMMUR-D4sIxy8pvgbGtN-mlmlX0sj-zJ8AS_EzhW-bCVt8UHoQMxp8i5W1-05',
       '0gmH-kIVFUMoB03I42lRuboW9bYLUBR_DSz8pzXjYxaIf1lOuk_RQav_7RzjeP7eKuzDMcLXrB',
       'oZs8KqqZXNUlC03Clledp5DHFhF5uLJ6pjZWgYzY3Jl4qJM84HGKwnVTxGlOzd1W_Xmrt7P',
       '1iZDacdhYhnZVAoCr8FBcagUxgL3gvdfGAgdTv-0s-9FmzhmbBw3RCTMFnJv_ZXMkZ8714',
       'qONcs9FWT2DJ7TLxboWeaz9N-XaSLaw84BGSWeIO69_vN59wWpxKjxed9KKPzB60dITEcSpErRT9Q',
       '96KlI28GW3Ww2p1vVD2hrmPBJJhgy1rU1m8LW5GnEPwGUnsEaqoaa68wGOAbIzwY-7e23ofcPCirrbTF',
       'ddk_mMJLM9fZcat70pWFg0WJcV4W4j_wT-_UqLs-DH36Oe9vvkhEkH3CVEXMdohA',
       '55gTlmZhIoMwgnXqoundp5ZMHVXNPBQxYIirUJVMlgEXmPWfze4nNmBbShQT-Tlikk',
       'p963iA-O6Qa9qb_VeV0LWxAfSMKV1_fg4GVC7zeUEBfPPGQrDLzPYy4Tbxiz-Lb',
       'rdApnnbWvIFsSSJNPpvU1Fj2uISRJvru3nX59Y96HkWB',
       'wFprBKt6YS9IX4VY8uGKQyw_JCZtCfHWG-r0wMzunckujc3P1yzMOqoXoq',
       '_qxJHGEaqzB6TII-tT0CUiOue1n6JMgXTzgPEs5fY

In [268]:
cleaned['COOKIES'].unique()

array([nan,
       '_gcl_au=1.1.74306004.1780433779; _gid=GA1.2.2122448978.1780433779; _gat_gtag_UA_67536040_1=1; _ga_TX92ZQKDXS=GS2.1.s1780433779$o1$g0$t1780433779$j60$l0$h0; _fbp=fb.1.1780433779434.379506095647138633; _clck=1ujucyg%5E2%5Eg6k%5E0%5E2344; _clsk=1lnqxnd%5E1780433780128%5E1%5E1%5Ez.clarity.ms%2Fcollect; _ga=GA1.2.1606822062.1780433779; _gat=1; previousUrl=prog.academy%2Fua%2Fstart',
       'previousUrl=prog.academy%2Fua%2Fstart-da',
       '_gcl_au=1.1.798810914.1777992389; _gid=GA1.2.1264228524.1777992389; _gcl_gs=2.1.k1$i1777992388$u149178871; _gac_UA-67536040-1=1.1777992394.CjwKCAjwqubPBhBOEiwAzgZX2nyHtTZXxsize4Gwr56nWRNSYsitFRCFjaFWwQFJ5vWDyQ9PEjUGCRoCdh0QAvD_BwE; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%2262962ee8-f0d9-4c08-9b41-8af35944d357%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _tt_enable_cookie=1; _

In [269]:
cleaned['Contact`s company'].unique()

array([nan, 'Company name not specified', 'Название не указано'],
      dtype=object)

In [270]:
cleaned['FORMID'].unique()

array([nan, 'form903852865', 'form1589907761', 'form832761338',
       'form585353266', 'form386680255', 'form386680324',
       'form2224655633', 'form1725743711', 'form386680340',
       'form402927681', 'form746407167', 'form386681322', 'form386680242',
       'form832761319', 'form386681409', 'form835935717', 'form417774864',
       'form417774833', 'form386686393', 'form585353325'], dtype=object)

In [271]:
cleaned['Modified by'].unique()

array(['Ivan M.', 'Vasyl F.', 'Oksana B.', 'Natalia H.', nan],
      dtype=object)

In [272]:
cleaned = cleaned.drop(columns =['gclid','COOKIES','Contact`s company'])

In [273]:
cleaned['manager'] = cleaned[
    ['Respons. user', 'Contact respons. user','Modified by']
].bfill(axis=1).iloc[:, 0]

cleaned = cleaned.drop(columns=[
    'Respons. user',
    'Contact respons. user',
    'Modified by'
])

In [274]:
cleaned['manager'].value_counts()

,count
manager,
Oksana B.,228
Natalia H.,218
Vasyl F.,211
Ivan M.,1


In [275]:
cleaned['manager'].isna().sum()

np.int64(0)

In [276]:
cleaned['utm_referrer'] = (
    cleaned['utm_referrer']
    .combine_first(cleaned['REFERER'])
    .combine_first(cleaned['referrer'])
)

cleaned = cleaned.drop(columns= [
    'REFERER',
    'referrer'
])

In [277]:
cleaned.columns

Index(['ID', 'Lead sale ₴', 'Created on', 'Modified on', 'Closed at', 'Tags',
       'Note 2', 'Lead stage', 'Fullname', 'Telegram', 'Оплата',
       'Lead scoring', 'Язык', 'FORMID', 'TRANID', 'Вопрос 1', 'Вопрос 2',
       'Вопрос 3', 'Вопрос 4', 'Вопрос 5', 'from', 'Created filled',
       'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content',
       'utm_referrer', 'phone', 'email', 'note_full', 'course_name',
       'manager'],
      dtype='object')

In [278]:
print(cleaned.shape)

(658, 33)


In [279]:
cleaned.to_csv('/content/drive/MyDrive/DA Internship ProgAcademy/Final version/cleaned.csv', index=False, encoding='utf-8-sig')

In [280]:
print("Saved locally (Google Drive). For GitHub usage, upload copy.csv or use raw link:")
print("https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/cleaned.csv")

Saved locally (Google Drive). For GitHub usage, upload copy.csv or use raw link:
https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/cleaned.csv
